import { serve } from "bun"; // Import Bun's built-in server
import { connectToDatabase, fetchDataFromPostgres, closeDatabaseConnection } from "./coredata.ts"; // Import database functions
import dotenv from "dotenv"; // Import dotenv to manage environment variables
import { OpenAI } from "openai"; // Import OpenAI client

dotenv.config(); // Load environment variables from .env file

// Initialize OpenAI client with API key from environment variables
const openai = new OpenAI(process.env.OPENAI_API_KEY);

/**
 * Summarizes the data fetched from the database.
 * @param {Array} data - The data fetched from the database.
 * @returns {Array} The summarized data.
 */
function summarizeData(data) {
    const summary = data.map(item => ({
        listing_id: item.listing_id,
        city: item.city,
        price: item.list_price,
        bedrooms: item.bedrooms_total,
        bathrooms: item.bathrooms_total,
        square_feet: item.living_area
    }));
    console.log('Summarized data:', summary);
    return summary;
}

/**
 * Constructs the prompt for the OpenAI API based on user input and the data fetched from the database.
 * @param {string} userInput - The user input.
 * @param {Array} data - The data fetched from the database.
 * @returns {string} The constructed prompt.
 */
function constructPrompt(userInput, data) {
    const summary = summarizeData(data);
    const prompt = `
    You are a master real estate mogul. Based on the following summarized data from the PostgreSQL database, provide data-driven suggestions for real estate investment strategies. Here is the data:

    ${JSON.stringify(summary, null, 2)}

    User input: ${userInput}

    Provide your suggestions:
    `;
    console.log('Constructed prompt:', prompt);
    return prompt;
}

/**
 * Generates suggestions from the OpenAI API based on the constructed prompt.
 * @param {string} prompt - The constructed prompt.
 * @returns {Promise<string>} The suggestions generated by the OpenAI API.
 */
async function generateSuggestions(prompt) {
    try {
        // Make a request to the OpenAI API with the constructed prompt
        const response = await openai.chat.completions.create({
            model: 'gpt-4', // Specify the OpenAI model
            messages: [{ role: 'system', content: 'You are a master real estate mogul consultant' }, { role: 'user', content: prompt }],
        });

        console.log('OpenAI API response:', response);

        // Check if the response contains choices and return the content of the first choice
        if (response.choices && response.choices.length > 0) {
            return response.choices[0].message.content;
        } else {
            throw new Error('No choices found in the response from OpenAI API');
        }
    } catch (error) {
        console.error('Error from OpenAI API:', error.response ? error.response.data : error.message);
        throw new Error('Failed to generate suggestions from OpenAI API');
    }
}

/**
 * Handles the incoming HTTP request to generate suggestions.
 * @param {Request} req - The incoming request.
 * @returns {Response} The response with the generated suggestions.
 */
async function handleGenerate(req) {
    let client;
    try {
        // Parse user input from the request body
        const { userInput } = await req.json();
        console.log('Received user input:', userInput);

        // Connect to the PostgreSQL database
        client = await connectToDatabase();

        // Fetch data from the database
        const data = await fetchDataFromPostgres(client, 10); // Fetch a limited number of rows

        // Construct the prompt for the OpenAI API
        const prompt = constructPrompt(userInput, data);

        // Generate suggestions using the OpenAI API
        const suggestions = await generateSuggestions(prompt);

        // Stream the suggestions back to the client
        const encoder = new TextEncoder();
        const stream = new ReadableStream({
            start(controller) {
                controller.enqueue(encoder.encode(JSON.stringify({ suggestions })));
                controller.close();
            }
        });

        console.log('Generated suggestions:', suggestions);
        return new Response(stream, {
            headers: {
                "Content-Type": "application/json",
                "Transfer-Encoding": "chunked"
            }
        });
    } catch (error) {
        console.error('Error generating suggestions:', error);
        return new Response(JSON.stringify({ error: 'Error generating suggestions', details: error.message }), { status: 500 });
    } finally {
        // Close the database connection if it was established
        if (client) {
            await closeDatabaseConnection(client);
        }
    }
}

// Start the Bun server and define request handling
serve({
    port: process.env.PORT || 5000,
    fetch(req) {
        const url = new URL(req.url);
        if (url.pathname === "/generate" && req.method === "POST") {
            return handleGenerate(req); // Handle POST requests to the /generate endpoint
        }
        return new Response("Not Found", { status: 404 }); // Return 404 for all other requests
    },
});

// Log the server start message
console.log(`Server running on port ${process.env.PORT || 5000}`);
